# Created with YamlCreate.ps1 v2.0.7 using InputObject 🤖 $debug=QUSU-7-2-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: SnapmakerDevTeam.SnapmakerLuban
PackageVersion: 4.3.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/parachvte/Luban/releases/download/v4.3.2-testing-add-publish-to-winget/Snapmaker-Luban-4.3.2-win-ia32.exe
  InstallerSha256: 16777A121936C6DEB5C25A84E19082CAA7B144CABB04A254F16948D5DE480EF7
- Architecture: x64
  InstallerUrl: https://github.com/parachvte/Luban/releases/download/v4.3.2-testing-add-publish-to-winget/Snapmaker-Luban-4.3.2-win-x64.exe
  InstallerSha256: 4B5A029B0D9EB2C41060B1739FEEC93247EA8A2F71467103B7D7DE3FAB786295
ManifestType: installer
ManifestVersion: 1.1.0
